cloud:
  aws:
    credentials:
      access-key: AKIAYPIVJTQP46NC5JVA
      secret-key: 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
      region:
        static: us-east-1
        auto: false

application :
  bucket:
    name: youtubetalents

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50
      max-request-size: 100

server:
  9301
